{
  "openapi": "3.0.1",
  "info": {
    "title": "ASC.Data.Backup",
    "version": "v2"
  },
  "servers": [
    {
      "url": "http://localhost:8092/",
      "description": "Local server"
    }
  ],
  "paths": {
    "/api/2.0/backup/getbackupschedule": {
      "get": {
        "tags": [
          "Backup"
        ],
        "summary": "Get the backup schedule",
        "operationId": "getBackupSchedule",
        "responses": {
          "200": {
            "description": "Backup schedule",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.BackupAjaxHandler_Schedule"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.BackupAjaxHandler_Schedule"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.BackupAjaxHandler_Schedule"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Returns the backup schedule of the current portal."
      }
    },
    "/api/2.0/backup/createbackupschedule": {
      "post": {
        "tags": [
          "Backup"
        ],
        "summary": "Create the backup schedule",
        "operationId": "createBackupSchedule",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupScheduleDto"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupScheduleDto"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupScheduleDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Boolean value: true if the operation is successful",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "boolean"
                }
              },
              "application/json": {
                "schema": {
                  "type": "boolean"
                }
              },
              "text/json": {
                "schema": {
                  "type": "boolean"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Creates the backup schedule of the current portal with the parameters specified in the request."
      }
    },
    "/api/2.0/backup/deletebackupschedule": {
      "delete": {
        "tags": [
          "Backup"
        ],
        "summary": "Delete the backup schedule",
        "operationId": "deleteBackupSchedule",
        "responses": {
          "200": {
            "description": "Boolean value: true if the operation is successful",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "boolean"
                }
              },
              "application/json": {
                "schema": {
                  "type": "boolean"
                }
              },
              "text/json": {
                "schema": {
                  "type": "boolean"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Deletes the backup schedule of the current portal."
      }
    },
    "/api/2.0/backup/startbackup": {
      "post": {
        "tags": [
          "Backup"
        ],
        "summary": "Start the backup",
        "operationId": "startBackup",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupDto"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupDto"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Backup progress: completed or not, progress percentage, error, tenant ID, backup progress item (Backup, Restore, Transfer), link",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Starts the backup of the current portal with the parameters specified in the request."
      }
    },
    "/api/2.0/backup/getbackupprogress": {
      "get": {
        "tags": [
          "Backup"
        ],
        "summary": "Get the backup progress",
        "operationId": "getBackupProgress",
        "responses": {
          "200": {
            "description": "Backup progress: completed or not, progress percentage, error, tenant ID, backup progress item (Backup, Restore, Transfer), link",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Returns the progress of the started backup."
      }
    },
    "/api/2.0/backup/getbackuphistory": {
      "get": {
        "tags": [
          "Backup"
        ],
        "summary": "Get the backup history",
        "operationId": "getBackupHistory",
        "responses": {
          "200": {
            "description": "List of backup history records",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupHistoryRecord"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupHistoryRecord"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupHistoryRecord"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Returns the history of the started backup."
      }
    },
    "/api/2.0/backup/deletebackup/{id}": {
      "delete": {
        "tags": [
          "Backup"
        ],
        "summary": "Delete the backup",
        "operationId": "deleteBackup",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Backup Id",
            "required": true,
            "schema": {
              "type": "string",
              "format": "uuid",
              "example": "75a5f745-f697-4418-b38d-0fe0d277e258"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Boolean value: true if the operation is successful",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "boolean"
                }
              },
              "application/json": {
                "schema": {
                  "type": "boolean"
                }
              },
              "text/json": {
                "schema": {
                  "type": "boolean"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Deletes the backup with the ID specified in the request."
      }
    },
    "/api/2.0/backup/deletebackuphistory": {
      "delete": {
        "tags": [
          "Backup"
        ],
        "summary": "Delete the backup history",
        "operationId": "deleteBackupHistory",
        "responses": {
          "200": {
            "description": "Boolean value: true if the operation is successful",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "boolean"
                }
              },
              "application/json": {
                "schema": {
                  "type": "boolean"
                }
              },
              "text/json": {
                "schema": {
                  "type": "boolean"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Deletes the backup history of the current portal."
      }
    },
    "/api/2.0/backup/startrestore": {
      "post": {
        "tags": [
          "Backup"
        ],
        "summary": "Start the restoring process",
        "operationId": "startBackupRestore",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupRestoreDto"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupRestoreDto"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.BackupRestoreDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Backup progress: completed or not, progress percentage, error, tenant ID, backup progress item (Backup, Restore, Transfer), link",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "asc_auth_key": [
              "read",
              "write"
            ]
          }
        ],
        "description": "Starts the data restoring process of the current portal with the parameters specified in the request."
      }
    },
    "/api/2.0/backup/getrestoreprogress": {
      "get": {
        "tags": [
          "Backup"
        ],
        "summary": "Get the restoring progress",
        "operationId": "getRestoreProgress",
        "responses": {
          "200": {
            "description": "Backup progress: completed or not, progress percentage, error, tenant ID, backup progress item (Backup, Restore, Transfer), link",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgress"
                }
              }
            }
          }
        },
        "description": "Returns the progress of the started restoring process."
      }
    }
  },
  "components": {
    "schemas": {
      "ASC.Data.Backup.ApiModels.BackupDto": {
        "type": "object",
        "properties": {
          "storageType": {
            "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupStorageType"
          },
          "storageParams": {
            "type": "object",
            "additionalProperties": {
              "nullable": true
            },
            "description": "Storage parameters",
            "nullable": true,
            "example": [
              {
                "key": {
                  "int": 1234,
                  "string": "some text",
                  "boolean": true
                },
                "value": {
                  "int": 1234,
                  "string": "some text",
                  "boolean": true
                }
              }
            ]
          },
          "dump": {
            "type": "boolean",
            "description": "Specifies if a dump will be created or not",
            "example": true
          }
        },
        "additionalProperties": false,
        "description": "Backup parameters"
      },
      "ASC.Data.Backup.ApiModels.BackupRestoreDto": {
        "type": "object",
        "properties": {
          "backupId": {
            "type": "string",
            "description": "Backup ID",
            "nullable": true,
            "example": "some text"
          },
          "storageType": {
            "type": "integer",
            "description": "Storage type",
            "format": "int32",
            "nullable": true,
            "example": 1234
          },
          "storageParams": {
            "type": "object",
            "additionalProperties": {
              "nullable": true
            },
            "description": "Storage parameters",
            "nullable": true,
            "example": [
              {
                "key": {
                  "int": 1234,
                  "string": "some text",
                  "boolean": true
                },
                "value": {
                  "int": 1234,
                  "string": "some text",
                  "boolean": true
                }
              }
            ]
          },
          "notify": {
            "type": "boolean",
            "description": "Notifies users about portal restoring process or not",
            "example": true
          }
        },
        "additionalProperties": false,
        "description": "Restoring parameters"
      },
      "ASC.Data.Backup.ApiModels.BackupScheduleDto": {
        "type": "object",
        "properties": {
          "storageType": {
            "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupStorageType"
          },
          "storageParams": {
            "type": "object",
            "additionalProperties": {
              "nullable": true
            },
            "description": "Storage parameters",
            "nullable": true,
            "example": [
              {
                "key": {
                  "int": 1234,
                  "string": "some text",
                  "boolean": true
                },
                "value": {
                  "int": 1234,
                  "string": "some text",
                  "boolean": true
                }
              }
            ]
          },
          "backupsStored": {
            "type": "integer",
            "description": "Maximum number of the stored backup copies",
            "format": "int32",
            "nullable": true,
            "example": 1234
          },
          "cronParams": {
            "$ref": "#/components/schemas/ASC.Data.Backup.ApiModels.Cron"
          },
          "dump": {
            "type": "boolean",
            "description": "Specifies if a dump will be created or not",
            "example": true
          }
        },
        "additionalProperties": false,
        "description": "Backup schedule parameters"
      },
      "ASC.Data.Backup.ApiModels.Cron": {
        "type": "object",
        "properties": {
          "period": {
            "$ref": "#/components/schemas/ASC.Data.Backup.BackupAjaxHandler_BackupPeriod"
          },
          "hour": {
            "type": "integer",
            "description": "Hour",
            "format": "int32",
            "example": 0
          },
          "day": {
            "type": "integer",
            "description": "Day",
            "format": "int32",
            "example": 0
          }
        },
        "additionalProperties": false,
        "description": "Cron parameters"
      },
      "ASC.Data.Backup.BackupAjaxHandler_BackupPeriod": {
        "oneOf": [
          {
            "enum": [
              "EveryDay",
              "EveryWeek",
              "EveryMonth"
            ],
            "type": "string",
            "description": "[EveryDay - Every day, EveryWeek - Every week, EveryMonth - Every month]",
            "example": "EveryDay"
          },
          {
            "enum": [
              0,
              1,
              2
            ],
            "type": "integer",
            "description": "[0 - Every day, 1 - Every week, 2 - Every month]",
            "example": 0
          }
        ]
      },
      "ASC.Data.Backup.BackupAjaxHandler_CronParams": {
        "type": "object",
        "properties": {
          "period": {
            "$ref": "#/components/schemas/ASC.Data.Backup.BackupAjaxHandler_BackupPeriod"
          },
          "hour": {
            "type": "integer",
            "format": "int32",
            "example": 1234
          },
          "day": {
            "type": "integer",
            "format": "int32",
            "example": 1234
          }
        },
        "additionalProperties": false
      },
      "ASC.Data.Backup.BackupAjaxHandler_Schedule": {
        "type": "object",
        "properties": {
          "storageType": {
            "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupStorageType"
          },
          "storageParams": {
            "type": "object",
            "additionalProperties": {
              "type": "string",
              "nullable": true
            },
            "nullable": true,
            "example": [
              {
                "key": "some text",
                "value": "some text"
              }
            ]
          },
          "cronParams": {
            "$ref": "#/components/schemas/ASC.Data.Backup.BackupAjaxHandler_CronParams"
          },
          "backupsStored": {
            "type": "integer",
            "format": "int32",
            "nullable": true,
            "example": 1234
          },
          "lastBackupTime": {
            "type": "string",
            "format": "date-time",
            "example": "2008-04-10T06:30:00.0000000+04:00"
          },
          "dump": {
            "type": "boolean",
            "example": false
          }
        },
        "additionalProperties": false
      },
      "ASC.Data.Backup.Contracts.BackupHistoryRecord": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid",
            "example": "e8d23e31-3323-4a2e-94a6-912e238446af"
          },
          "fileName": {
            "type": "string",
            "nullable": true,
            "example": "some text"
          },
          "storageType": {
            "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupStorageType"
          },
          "createdOn": {
            "type": "string",
            "format": "date-time",
            "example": "2008-04-10T06:30:00.0000000+04:00"
          },
          "expiresOn": {
            "type": "string",
            "format": "date-time",
            "example": "2008-04-10T06:30:00.0000000+04:00"
          }
        },
        "additionalProperties": false
      },
      "ASC.Data.Backup.Contracts.BackupProgress": {
        "type": "object",
        "properties": {
          "isCompleted": {
            "type": "boolean",
            "example": true
          },
          "progress": {
            "type": "integer",
            "format": "int32",
            "example": 1234
          },
          "error": {
            "type": "string",
            "nullable": true,
            "example": "some text"
          },
          "link": {
            "type": "string",
            "nullable": true,
            "example": "some text"
          },
          "tenantId": {
            "type": "integer",
            "format": "int32",
            "example": 1234
          },
          "backupProgressEnum": {
            "$ref": "#/components/schemas/ASC.Data.Backup.Contracts.BackupProgressEnum"
          },
          "taskId": {
            "type": "string",
            "nullable": true,
            "example": "some text"
          }
        },
        "additionalProperties": false
      },
      "ASC.Data.Backup.Contracts.BackupProgressEnum": {
        "oneOf": [
          {
            "enum": [
              "Backup",
              "Restore",
              "Transfer"
            ],
            "type": "string",
            "description": "[Backup - Backup, Restore - Restore, Transfer - Transfer]",
            "example": "Backup"
          },
          {
            "enum": [
              0,
              1,
              2
            ],
            "type": "integer",
            "description": "[0 - Backup, 1 - Restore, 2 - Transfer]",
            "example": 0
          }
        ]
      },
      "ASC.Data.Backup.Contracts.BackupStorageType": {
        "oneOf": [
          {
            "enum": [
              "Documents",
              "ThridpartyDocuments",
              "CustomCloud",
              "Local",
              "DataStore",
              "ThirdPartyConsumer"
            ],
            "type": "string",
            "description": "[Documents - Documents, ThridpartyDocuments - Thridparty documents, CustomCloud - Custom cloud, Local - Local, DataStore - Data store, ThirdPartyConsumer - Thirdparty consumer]",
            "example": "Documents"
          },
          {
            "enum": [
              0,
              1,
              2,
              3,
              4,
              5
            ],
            "type": "integer",
            "description": "[0 - Documents, 1 - Thridparty documents, 2 - Custom cloud, 3 - Local, 4 - Data store, 5 - Thirdparty consumer]",
            "example": 0
          }
        ]
      }
    },
    "securitySchemes": {
      "asc_auth_key": {
        "type": "apiKey",
        "name": "asc_auth_key",
        "in": "cookie"
      }
    }
  },
  "tags": [
    {
      "name": "Backup",
      "description": "Operations for working with backup"
    }
  ]
}